openapi: 3.0.0
info:
  title: Auth API
  description: API for user authentication and authorization
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthDto'
      responses:
        '201':
          description: User registered successfully
        '409':
          description: Email already registered
        '400':
          description: Bad request
  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginAuthDto'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'
        '401':
          description: Unauthorized
  /auth/roles:
    get:
      summary: Get user roles
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User roles retrieved successfully
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
components:
  schemas:
    CreateAuthDto:
      type: object
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
        password:
          type: string
          format: password
    LoginAuthDto:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    LoginResponseDto:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
              format: email
            name:
              type: string
            role:
              type: string
        access_token:
          type: string
