openapi: 3.0.0
info:
  title: Products API
  description: API for managing products
  version: 1.0.0
paths:
  /products:
    get:
      summary: Retrieve all products
      parameters:
        - name: includeInactive
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductDto'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Retrieve a single product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    patch:
      summary: Update a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductDto'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    delete:
      summary: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        purchasePrice:
          type: number
        sellingPrice:
          type: number
        finalPrice:
          type: number
        marginPercent:
          type: number
        isIvaExempt:
          type: boolean
        isActive:
          type: boolean
        deletedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        Category:
          $ref: '#/components/schemas/Category'
        Supplier:
          $ref: '#/components/schemas/Supplier'
        PriceHistory:
          type: array
          items:
            $ref: '#/components/schemas/PriceHistory'
        Inventory:
          type: array
          items:
            $ref: '#/components/schemas/Inventory'
    CreateProductDto:
      type: object
      required:
        - name
        - purchasePrice
        - marginPercent
        - categoryId
        - supplierId
      properties:
        name:
          type: string
        purchasePrice:
          type: number
        marginPercent:
          type: number
        sku:
          type: string
        hasExtraTax:
          type: boolean
        extraTaxRate:
          type: number
        isIvaExempt:
          type: boolean
        stock:
          type: number
        categoryId:
          type: string
        supplierId:
          type: string
    UpdateProductDto:
      type: object
      properties:
        name:
          type: string
        purchasePrice:
          type: number
        marginPercent:
          type: number
        sku:
          type: string
        hasExtraTax:
          type: boolean
        extraTaxRate:
          type: number
        isIvaExempt:
          type: boolean
        stock:
          type: number
        categoryId:
          type: string
        supplierId:
          type: string
