services:
  - type: web
    name: inventory-pos-api
    env: node
    buildCommand: npm install && npm run build:prod
    startCommand: node dist/main.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sgc-backend-db
          property: connectionString
