
services:
  - type: web
    name: inventory-pos-api
    env: node
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sgc-backend-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
