name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Set Environment Variables
        run: echo "Setting environment variables"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Tests
        run: npm test -- --passWithNoTests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Lint Code
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Run Code Coverage
        run: npm run test:cov
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            ${{ secrets.RENDER_DEPLOY_HOOK_PRODUCTION }}
