name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
  push:
    branches:
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      #- name: Lint Code
       # run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Deploy to Render (Only for Main)
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{}' \
            https://api.render.com/v1/services/<your-service-id>/deploys
