name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Set Environment Variables
        run: echo "Setting environment variables"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Tests
        run: npm test --config=jest.config.cjs --passWithNoTests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Lint Code
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Trigger Render Deploy Hook
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            ${{ secrets.RENDER_DEPLOY_HOOK }}
